#!/bin/bash
export dir="/root/JLTimer/timer"
bannerPrompt=$(cat settings | grep "bannerPrompt")
showBanner=$(cat settings | grep "showBanner")

currentLine () {
	echo -en "\E[6n"
	read -sdR CURPOS
	CURPOS=${CURPOS#*[}
	curLine=$(echo $CURPOS | grep -E -o ".{0,100};.{0,0}" | tr ";" " ")
	export curLine
}

showBannerPrompt () {
	tput bold
	echo "Do you want to see the banner every time you start this programm?"
	echo -en "y or n: "
	tput sgr0
	read -r showBannerYorN
	tput bold
	case "$showBannerYorN" in
		y) 
			echo "bannerPrompt=false" >> settings
			echo "showBanner=true" >> settings
			echo 'Your answer is saved. You can change this with "timer -b or -banner"';;
		n)
			echo "bannerPrompt=false" >> settings
			echo "showBanner=false" >> settings
			echo 'Your answer is saved. You can change this with "timer -b or -banner"';;
		*) 
			echo "invalid input. You have to enter y or n."
			exit 1;;
	esac
}
if [ $showBanner != "false"]; then
	echo "     ██╗██╗  ████████╗██╗███╗   ███╗███████╗██████╗ "
	echo "     ██║██║  ╚══██╔══╝██║████╗ ████║██╔════╝██╔══██╗"
	echo "     ██║██║     ██║   ██║██╔████╔██║█████╗  ██████╔╝"
	echo "██   ██║██║     ██║   ██║██║╚██╔╝██║██╔══╝  ██╔══██╗"
	echo "╚█████╔╝███████╗██║   ██║██║ ╚═╝ ██║███████╗██║  ██║"
	echo " ╚════╝ ╚══════╝╚═╝   ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝"
fi
if [ -z $showBannerPrompt ]; then
	showBannerPrompt 
fi
if [ -z $1 ]; then
	tput bold
	echo "How many seconds should the timer run?"
	tput sgr0
	read -r userInputTime
else
	userInputTime=$1
fi
showTime=$userInputTime
tput bold
echo "Timer:"
currentLine #function
for (( $showTime; $userInputTime >= $showTime; showTime-- )); do
	tput cup $(($curLine - 1)) 0
	echo -ne "\033[K$showTime"
	if [ $showTime == 0 ]; then
		break
	fi
	sleep 1
done
trap "break" SIGINT
currentLine #function
while true; do
	tput bold
	tput setaf 4 #blue
	tput cup $curLine 0
	echo -ne "BEEP"
	sleep 0.2
	tput setaf 1 #red
	tput cup $curLine 0
	echo -ne "BEEP"
	sleep 0.2
done
tput setaf 7
tput sgr0
echo " "
exit
